VogueNation/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' ,include('core.urls'))
]

Voguenation25/urls.py
from django.contrib import admin
from django.urls import path,include
from vogue import views

urlpatterns = [
    path("",views.landing_page,name='landing_page'),
    path("admin/", admin.site.urls),
    path('vogue/', include('vogue.urls'))
]

core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # path('register/', views.register,name = 'vogue-register'),
    path('register/<str:competition_name>/',  views.register, name='register'),
    path('', views.home,name = 'Vogue-Home'),
    path('data/<str:comp>', views.data,name = 'data'),

]

core/models.py
from django.db import models
from django.core.validators import MinValueValidator

class Competition(models.Model):
    competition_name = models.CharField(max_length=255)

    def __str__(self):
        return self.competition_name

class Role(models.Model):
    name_of_role = models.CharField(max_length=255)
    min_member = models.IntegerField(validators=[MinValueValidator(0)])
    max_member = models.IntegerField(validators=[MinValueValidator(1)])
    competitions = models.ForeignKey(Competition, on_delete=models.CASCADE)

    def __str__(self):
        return self.name_of_role

class Team(models.Model):
    team_name = models.CharField(max_length=255)
    competition = models.ForeignKey(Competition, on_delete=models.CASCADE)
    prev_performance = models.CharField(max_length=255, null=True, blank=True)


    def __str__(self):
        return self.team_name

class Member_Detail(models.Model):
    GENDER_CHOICES = (
        ('f', 'Female'),
        ('m', 'Male'),
        ('o', 'Others')
    )

    name = models.CharField(max_length=255)
    competition = models.ForeignKey(Competition, on_delete=models.CASCADE)
    email = models.EmailField(max_length=254)
    phone_number = models.CharField(max_length=20)
    your_city = models.CharField(max_length=255)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    role = models.ForeignKey(Role, on_delete=models.CASCADE)
    Postal_code = models.IntegerField(null=True,blank=True)
    is_leader = models.BooleanField(default=False)

    def __str__(self):
        return self.name

core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Role, Competition, Member_Detail, Team
from django.contrib import messages
from django.contrib.auth.decorators import login_required

def home(request):
    return render(request, 'core/vog_home.html')


def register(request,competition_name):
    if request.method == "POST":
        prev_performance = request.POST.get('performance')
        team_name = request.POST.get('team_name')
        your_city = request.POST.get('your_city')
        competition = get_object_or_404(Competition,competition_name=competition_name)
        postal_code = request.POST.get('postal_code')
        names = request.POST.getlist('name')
        emails = request.POST.getlist('Email')
        phone_numbers = request.POST.getlist('Phone_Number')
        genders = request.POST.getlist('gender')
        role_ids = request.POST.getlist('role')
        num_participants = len(names)
        team = Team.objects.create(
            team_name=team_name,
            competition=competition, 
            prev_performance=prev_performance 
        )
        competitionss = Competition.objects.get(competition_name=competition_name)
        roles = Role.objects.filter(competitions=competitionss)
        competitions = Competition.objects.all()
        print(names)
        # role_counts = {}
        # for i in range(len(names)):
        #     name = names[i]
        #     email = emails[i]
        #     phone_number = phone_numbers[i]

        #     # Validate name
        #     if not name or not (email) or not phone_number or not team_name or  not phone_number.isdigit():
        #         messages.error(request, f"Please enter All nessacary details properly")

        #         return render(request, 'core/reg_vog.html', {
        #         'competition' : competition_name,
        #         'roles': roles,
        #         'competitions': competitions,
        #         })
        # for role in roles:
        #     role_counts[role]=0
        # for i in range(num_participants):
        #     role_counts[role]+=1
        # for role, count in role_counts.items():
        #     if count < role.min_member:
        #         messages.error(request, f'The role {role} requires at least {role.min_member} participants.')
        #         return render(request, 'core/reg_vog.html', {
        #         'roles': roles,
        #         'competitions': competitions,
        #         })
        team.save()
        for i in range(num_participants):
            role = get_object_or_404(Role, pk=int(role_ids[i]))
            memberdetails = Member_Detail.objects.create(
                name=names[i],
                email=emails[i],
                phone_number=phone_numbers[i],
                your_city=your_city,
                gender=genders[i],
                competition=competition,
                role=role,
                team=team,
                Postal_code=postal_code if postal_code else None,
                is_leader=(i == 0)  # First member is the leader
            )
            memberdetails.save()
        

        messages.success(request,'Your team has been registered successfully')
        return redirect('Vogue-Home')
    
    competitions = Competition.objects.all()
    competitionss = Competition.objects.get(competition_name=competition_name)
    roles = Role.objects.filter(competitions=competitionss)
    return render(request, 'core/reg_vog.html', {
        'competition' : competition_name,
        'roles': roles,
        'competitions': competitions,
    })
@login_required(login_url='Vogue-Home')
def data(request,comp):
    competition = Competition.objects.get(competition_name=comp)
    Teams=Team.objects.filter(competition=competition)
    return render(request, 'core/data.html',{"teams": Teams});

templates/core/data.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <table>
      <thead>
        <tr>
          <th>Team Name</th>
          <th>Performance</th>
          <th>Leader Name</th>
          <th>Leader email</th>
          <th>Leader Phone</th>
          <th>Leader City</th>
          <th>Leader Role</th>
          <th>Members</th>
        </tr>
      </thead>
      <tbody>
        <style>
          table {
            width: 100%;
            border-collapse: collapse;
          }
          th, td {
            padding: 8px;
            text-align: left;
            border-bottom: 1px solid #ddd;
          }
          tr:hover {
            background-color: #f5f5f5;
          }
        </style>
        {% for team in teams %}
          <tr>
            <td>{{ team.team_name }}</td>
            <td>{{ team.prev_performance }}</td>
            <td>{{ team.member_detail_set.all.0.name }}</td>
            <td>{{ team.member_detail_set.all.0.email }}</td>
            <td>{{ team.member_detail_set.all.0.phone_number }}</td>
            <td>{{ team.member_detail_set.all.0.your_city }}</td>
            <td>{{ team.member_detail_set.all.0.role }}</td>
            <td>
              {% for mem in team.member_detail_set.all %}
                {{ mem.name }},
                {{ mem.email }},
                {{ mem.phone_number }},
                {{ mem.your_city }},
                {{ mem.role }}<br>
              {% endfor %}
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </body>
</html>

templates/core/reg_voga.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Registration</title>
    <link rel="stylesheet" type="text/css "href="{% static
    "core/reg_vog.css" %} ">
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/intl-tel-input@18.2.1/build/css/intlTelInput.css"
    />
    <link rel="icon" type="image/x-icon" href="{% static 'core/images/VN Logo.png' %}" />

  </head>

  <body>
    <div class="container-1">
      <div class="header">
        <div class="logo-container">
          <img src="{% static "core/Group 19.png" %}" class="logo">
        </div>
        <p class="name-1">REGISTRATIONS</p>
        <button class="back" id="item_">BACK</button>
      </div>
    </div>
    <div class="line"></div>
    <div class="events">
      <div class="container-2">
        <div class="events-name" id="com1">
          <a class="competition" href="/register/Haute_Couture/"
            >Haute Couture</a
          >
        </div>
        <div class="events-name comm" id="com2">
          <a class="competition" href="/register/States_of_Dress/"
            >States of Dress</a
          >
        </div>
        <div class="events-name" id="com3">
          <a class="competition" href="/register/Glamour_Nova/">Glamour Nova</a>
        </div>
      </div>
    </div>
    {% if messages.error %} {% for message in messages.error %}
    <div class="alert alert-warning">{{ message }}</div>
    {% endfor %} {% endif %}
    <form name="reg-form" id="add-container" method="POST">
      {% csrf_token %}
      <div class="team_container">
        <div class="team_name">
          <h1 class="txt-1">Team Name&nbsp;<a>*</a></h1>
          <input type="text" class="input-box" name="team_name" />
        </div>
        <div class="team_name">
          <h1 class="txt-1">Previous Performance&nbsp;<a>*</a></h1>
          <input type="text" class="input-box" name="performance" />
        </div>
      </div>
      <div class="leader">
        <div class="leader-text">
          <!-- <div>
                    <p>Team Name&nbsp;<a>*</a></p><input class="input-box" type="text" name="team_name">
                </div> -->
          <p class="txt-1">Leader Details</p>
          <div class="line-2"></div>
          <p class="txt-2">
            All fields marked with&nbsp;<a>*</a>&nbsp;are mandatory
          </p>
        </div>
      </div>
      <div id="add-container_2">
        <div class="form-container">
          <div action="" class="form-box">
            <div>
              <p>Name&nbsp;<a>*</a></p>
              <input class="input-box" type="text" name="name" />
            </div>
            <div class="align-right">
              <p>Gender&nbsp;<a>*</a></p>
              <select id="select" class="input-box" name="gender">
                <option value="m">Male</option>
                <option value="f">Female</option>
                <option value="o">Others</option>
              </select>
              <img class="img-set" src="{% static "core/Vector 6.png" %}"
              alt="">
            </div>
            <div>
              <p>Contact Number&nbsp;<a>*</a></p>
              <input
                id="phone"
                class="input-box phone1"
                type="tel"
                placeholder="01234 56789"
                name="Phone_Number"
              />
            </div>
            <div class="align-right">
              <p>Email ID&nbsp;<a>*</a></p>
              <input class="input-box" type="email" name="Email" />
            </div>
            <div>
              <p>Role&nbsp;<a>*</a></p>
              <select id="select" class="input-box" name="role">
                {% for role in roles %}
                <option value="{{ role.id }}">{{ role.name_of_role}}</option>
                {% endfor %}
              </select>
              <img class="img-set-2" src="{% static "core/Vector 6.png" %}"
              alt="">
            </div>
            <div class="align-right">
              <p>City&nbsp;<a>*</a></p>
              <input class="input-box" type="text" name="your_city" />
            </div>
          </div>
        </div>
        <div class="gap-1"></div>
        <div class="leader">
          <div class="leader-text">
            <div class="finally">
              <div class="hax">Members 1 Details</div>
            </div>
            <p class="txt-2 padding">
              All fields marked with&nbsp;<a>*</a>&nbsp;are mandatory
            </p>
          </div>
        </div>
        <div class="form-container">
          <div action="" class="form-box-1 mem" name="myform">
            <div>
              <p>Name&nbsp;<a>*</a></p>
              <input class="input-box" type="text" name="name" />
            </div>
            <div class="align-right">
              <p>Gender&nbsp;<a>*</a></p>
              <select id="select" class="input-box" name="gender">
                <option value="m">Male</option>
                <option value="f">Female</option>
                <option value="o">Others</option>
              </select>
              <img class="img-set" src="{% static "core/Vector 6.png" %}"
              alt="">
            </div>
            <div>
              <p>Contact Number&nbsp;<a>*</a></p>
              <input
                id="phone-1"
                class="input-box phone1"
                type="tel"
                placeholder="01234 56789"
                name="Phone_Number"
              />
            </div>
            <div class="align-right">
              <p>Email ID&nbsp;<a>*</a></p>
              <input class="input-box" type="email" name="Email" />
            </div>
            <div>
              <p>Role&nbsp;<a>*</a></p>
              <select id="select" class="input-box" name="role">
                {% for role in roles %}
                <option value="{{ role.id }}">{{ role.name_of_role}}</option>
                {% endfor %}
              </select>
              <img class="img-set-2" src="{% static "core/Vector 6.png" %}"
              alt="">
            </div>
          </div>
        </div>
      </div>

      <div class="member-container">
        <div class="member-box">
          <button type="button" class="btn" id="press-1">MEMBER +</button>
          <button type="button" class="btn" id="press-2">MEMBER -</button>
        </div>
      </div>
      <div class="register-box">
        <button class="btn-2">REGISTER</button>
      </div>
    </form>
    {% comment %}
    <div class="black" style="display: none">
      <div class="popup">
        <div class="atn">Attention</div>
        <div class="dis"></div>
        <button id="cls">CLOSE</button>
      </div>
    </div>
    {% endcomment %} {% if messages %}
    <div class="black">
      <div class="popup">
        <div class="atn">Attention</div>
        {% for message in messages %}
        <div class="dis">{{ message }}</div>
        {% endfor %}
        <button id="cls">CLOSE</button>
      </div>
    </div>
    {% endif %}
  </body>
  <script></script>
  <script src="https://cdn.jsdelivr.net/npm/intl-tel-input@18.2.1/build/js/intlTelInput.min.js"></script>
  <script>
    const input = document.querySelector("#phone");
    window.intlTelInput(input, {
      utilsScript:
        "https://cdn.jsdelivr.net/npm/intl-tel-input@18.2.1/build/js/utils.js",
      initialCountry: "in",
      separateDialCode: true,
    });

    const input_1 = document.querySelector("#phone-1");
    window.intlTelInput(input_1, {
      utilsScript:
        "https://cdn.jsdelivr.net/npm/intl-tel-input@18.2.1/build/js/utils.js",
      initialCountry: "in",
      separateDialCode: true,
    });
  </script>
  <script>
    document.getElementById('item_').addEventListener('click', function() {
        window.location.href = '/';
    });

    document.getElementById('press-1').addEventListener("click", addPage);
    document.getElementById('press-2').addEventListener("click", deletePage);
    const container = document.getElementById('add-container_2');
    let removeBtn = document.getElementById('press-2');
    var count = 1;
    function addPage() {
        count++;
        var code= `
        <div class="leader">
                <div class="leader-text">
                    <div class="finally"><div class="hax">Members ${count} Details
                    </div></div>
                    <p class="txt-2 padding">All fields marked with&nbsp;<a>*</a>&nbsp;are mandatory</p>
                </div>
        </div>
        <div class="form-container">
        <div action="" class="form-box-1 mem">
        <div>
            <p>Name&nbsp;<a>*</a></p><input class="input-box ibox" type="text" name="name">
        </div>
        <div class="align-right">
            <p>Gender&nbsp;<a>*</a></p>
            <select name="gender" id="select" class="input-box">
                        <option value="m">Male</option>
                        <option value="f">Female</option>
                        <option value="o">Others</option>
                    </select>
                    <img class="img-set" src="{% static "core/Vector 6.png" %}" alt="">
        </div>
        <div>
            <p>Contact Number&nbsp;<a>*</a></p><input id="phone-${count}" class="input-box phone1 ibox" type="tel" placeholder="01234 56789" name="Phone_Number">
        </div>
        <div class="align-right">
            <p>Email ID&nbsp;<a>*</a></p><input class="input-box ibox" type="email" name="Email">
        </div>
        <div>
            <p>Role&nbsp;<a>*</a></p>
            <select  id="select" class="input-box" name="role">
                {% for role in roles %}
                <option value="{{ role.id }}">{{ role.name_of_role}}</option>
                {% endfor %}
            </select>
            <img class="img-set-2" src="{% static "core/Vector 6.png" %}" alt="">
        </div>
    </div>
    </div>
    </div>`;

    container.insertAdjacentHTML("beforeend", code);

        if (count == 2) {
            removeBtn.style.display =   "inline-block";
        }

        const input = document.querySelector(`#phone-${count}`);
        window.intlTelInput(input, {
            utilsScript: "https://cdn.jsdelivr.net/npm/intl-tel-input@18.2.1/build/js/utils.js",
            initialCountry: "in",
            separateDialCode: true,
        });
    }

    function deletePage() {
        count--;
        let elm = container.lastElementChild;
        let elm2 = container.lastElementChild.previousElementSibling;
        container.removeChild(elm);
        container.removeChild(elm2);

        if (count == 1) {
            removeBtn.style.display = "none";
        }
    }

    const linkPage = window.location.pathname;
    const com1 = document.getElementById("com1");
    const com2 = document.getElementById("com2");
    const com3 = document.getElementById("com3");

    function addClassOnClick(element1, element2, element3) {
        element1.classList.add("comm");
        element2.classList.remove("comm");
        element3.classList.remove("comm");

    };
    if (linkPage == com1.firstElementChild.pathname) {
    addClassOnClick(com1, com2, com3);
    }
    if (linkPage == com2.firstElementChild.pathname) {
        addClassOnClick(com2, com1, com3);
    }
    if (linkPage== com3.firstElementChild.pathname) {
        addClassOnClick(com3, com1, com2);
    }
    const popup = document.querySelectorAll('.black')[0]
    popup.addEventListener("click", function(){
        popup.style.display="none";
    });

    document.forms['reg-form'].onsubmit= function(event){

        let nameInputs = document.querySelectorAll('.ibox');
        // let phone = document.querySelectorAll('.name1');
        for (var i = 0; i < nameInputs.length; i++) {
            if (nameInputs[i].value.trim() === "") {
                document.querySelector(".dis").innerHTML = "Enter All necessary details Properly";
                document.querySelector(".black").style.display = "block";
                event.preventDefault();
                return false;
            }
        }
        var numInputs = document.querySelectorAll('input[type="tel"]');
        for (var i = 0; i < numInputs.length; i++) {
            if (isNaN(numInputs[i].value.trim())) {
                document.querySelector(".dis").innerHTML = "Enter All necessary details Properly";
                document.querySelector(".black").style.display = "block";
                event.preventDefault();
                return false;
            }
        }
        var roleCount = {};
        {% for role in roles  %}
            roleCount[{{role.id}}] = 0;
        {% endfor%}
        console.log(roleCount);
        const roleDropdowns = document.querySelectorAll('select[name="role"]');


        // Iterate through each role dropdown
        roleDropdowns.forEach((dropdown) => {
            // Get the selected role value
            const selectedRole = dropdown.value;

            // If the selected role is not empty
            if (selectedRole) {
                // Increment the count for the selected role in the roleCount object
                roleCount[selectedRole] = (roleCount[selectedRole] || 0) + 1;
            }
        });
        console.log(roleCount);
        {% for role in roles  %}
            var name = "{{role.name_of_role}}";
            var minmem = {{role.min_member}};
            if (roleCount[{{role.id}}] < {{role.min_member}}){
                document.querySelector(".dis").innerHTML = `The role ${name} requires at least ${minmem} participants`;
                document.querySelector(".black").style.display = "block";
            event.preventDefault();
                return false;
            }
        {% endfor%}
            console.log("After role count initialization");
    }
  </script>
</html>